document.getElementById("checkButton").addEventListener("click", function () {
  const name = document.getElementById("nameInput").value;

  if (!name) {
    Swal.fire({
      icon: "warning",
      title: "Waduh...",
      text: "Namanya diisi kocag.",
    });
    return;
  }

  const khodams = [
    "Macan Putih",
    "Naga Biru",
    "Garuda Emas",
    "Skibidi Toilet",
    "Anies",
    "Sempak Firaun",
    "Charger Laptop",
    "Speaker Bluetooth",
    "Korek Gas",
    "Gajah Gembiraloka",
    "Sigma Man😎",
    "Kera Sakti",
    "Burung Hantu",
    "Ular Kasur",
    "Rajawali",
    "Rubah",
    "Ikan Berkaki Sikil",
    "Palu Firaun",
    "Infinix Note 30 pro",
    "Mouse",
    "Keyboard Dajjal",
    "Tupperware",
    "Kucing Merah",
    "Tikus Besi",
    "Realme Note 5",
    "Jangkrik Emas",
    "Katak Awikwok",
    "Squitwet",
    "Singa Putih",
    "Tuan Crab",
    "Spongebob",
    "Coca Cola",
    "Fanta",
    "Pompa Angin 300 psi",
    "RTX 4090",
    "Motherboard",
    "RAM 8GB 3666Mhz",
    "Kalajengking Hitam",
    "lampion terbang",
    "kulkas mini",
    "mixer serbaguna",
    "helm cakil",
    "gelas kaca",
    "tiket kereta api",
    "laptop gaming",
    "permen karet raksasa",
    "sepeda listrik viar",
    "SCP 173",
    "kak gem",
    "sigit rendang",
    "mas rusdi",
    "robot penjaga rumah",
    "nyi roro wetan",
    "ojek online",
    "goblin ",
    "mesin penanak nasi",
    "smartwatch apple",
    "kursi pijet",
    "vacuum cleaner",
    "lampu tidur",
    "tv led",
    "speaker bluetooth",
    "headset wireless rexus",
    "redmi note 9",
    "blender otomatis",
    "sajadah elektrik",
    "kipas angin merk cosmos",
    "tempat tidur",
    "kulkas portable samsung",
    "samsung s24 ultra",
    "setrika uap polytron",
    "filosofi teras",
    "iphone 18 pro max",
    "ac portable",
    "cctv hotel",
    "ganjar",
    "john wick",
    "handuk super lembut",
    "jokowi",
    "tempat sampah otomatis",
    "michael jackson",
    "alan walker",
    "kai cenat",
    "kendrick lammar",
    "sigma skibidi",
    "anies",
    "kak gem",
    "uni bakwan",
    "el gasing",
    "ronaldo",
    "sapu ijuk",
    "penghisap debu",
    "minyak telon",
    "kucing hitam",
    "sarung tangan",
    "ayam kampus",
    "sigma male 😋",
    "pewangi ruangan",
  ];

  const randomIndex = Math.floor(Math.random() * khodams.length);
  const khodamTerdeteksi = khodams[randomIndex];

  const pesan = `Alamak ${name} 😱, di dalam dirimu ada khodam ${khodamTerdeteksi}. 😨`;

  Swal.fire({
    title: "Hasil Cek Khodam",
    text: pesan,
    icon: "info",
  });
});
